name: Publish Release

on: 
  pull_request: 
    types: [closed]

jobs:
  publish-releases:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: INIT
        if: ${{ github.event.label.name == 'pr/release' }}
        uses: actions/checkout@v2

      - name: Publish Release
        run: |
          echo "${{ github.ref == 'release/*' }}"
          echo "${{ github.event.pull_request.merged }}"
