name: Publish Release

on: 
  pull_request: 
    types: [closed]

jobs:
  publish-releases:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: INIT
        if: ${{ github.base_ref == 'refs/heads/release/*'  }}
        uses: actions/checkout@v2

      - name: Publish Release
        run: |
          echo "${{ github.base_ref }}"
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}" 
          echo "${{ github.event.pull_request.merged }}"
