name: Publish Release

on: 
  pull_request: 
    types: [closed]

jobs:
  publish-releases:
    if: ${{ github.event.label.name == 'pr/release' && github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Release
        run: |
          echo "${{ (github.event.label.name == 'pr/release' }}"
          echo "${{ (github.event.label.merged == 'pr/release' }}"
          echo "------------"
          echo "${{ (github.event.label.name == 'pr/release' }}"
          echo "${{ (github.event.label.merged == 'pr/release' }}"
          echo "-----------"
          echo "${{ (github.event.label.name == 'pr/release' &&  github.event.pull_request.merged == false) }}"

